# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Pages
on:
  workflow_dispatch:
    inputs:
      local_dev:
        description: "Local development"
        required: false
        default: "false"
        type: boolean
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: wranders/markdown-to-pages-action@v1
      with:
        out_path: out
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-pages-artifact@v4
      if: ${{ !inputs.local_dev }}
      with:
        path: out
  deploy:
    needs: build
    if: ${{ !inputs.local_dev }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
